CREATE TABLE TB_PESSOA (
idCadastroPessoa INTEGER NOT NULL,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(14) NOT NULL,
RG VARCHAR(25) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
RUA VARCHAR(80) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
ESTADO CHAR(2) NOT NULL,
NUMERO VARCHAR(20) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
CEP VARCHAR(30) NOT NULL,
PONTOREFERENCIA VARCHAR(150) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
CONSTRAINT PK_IDCADASTRO PRIMARY KEY (idCadastroPessoa)
);





commit